# Generated by Django 3.2 on 2022-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220415_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
