# Generated by Django 3.2 on 2022-05-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_customer_id', models.CharField(max_length=255)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('customer_business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_address_1', models.CharField(max_length=50)),
                ('customer_address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_town_or_city', models.CharField(max_length=50)),
                ('customer_county', models.CharField(max_length=50)),
                ('customer_postcode', models.CharField(max_length=50)),
                ('customer_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
