# Generated by Django 3.2 on 2022-05-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20220502_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecustomer',
            name='user',
        ),
    ]
