# Generated by Django 3.2 on 2022-05-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0007_alter_invoicecustomer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MakeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_info', models.TextField()),
                ('invoice_subtotal', models.FloatField()),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicecustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
