# Generated by Django 3.2 on 2022-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(default='Date', max_length=20),
            preserve_default=False,
        ),
    ]
