# Generated by Django 3.2 on 2022-04-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20220428_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='trial_ends',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='trial_starts',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='trial_subs',
        ),
    ]
