# Generated by Django 3.2 on 2022-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, default='noimage_co3ypm', null=True, upload_to=''),
        ),
    ]
