# Generated by Django 3.2 on 2022-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
