# Generated by Django 3.2 on 2022-05-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_plan_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image_alt',
        ),
    ]
